// <auto-generated />
namespace Tarbya.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class imageEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "201905312337472_imageEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
